[package]
name = "PlayBridgeADB"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.40"
ctor = "0.6.3"
image = "0.25.9"
imageproc = "0.25.0"
once_cell = "1.21.3"
open = "5.3.3"
regex = "1.11.1"
spin_sleep = "1.3.3"
win-screenshot = "4.0.14"
windows = { version = "0.62.2", features = [
    "Win32_Foundation",
    "Win32_UI_HiDpi",
    "Win32_UI_WindowsAndMessaging",
] }
winreg = "0.55.0"
winrt-toast = "0.1.1"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true
