name: release PlayBridge

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_release:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-msvc
          override: true

      - name: Generate KST datetime-based version tag
        id: version_tag
        shell: pwsh
        run: |
          $kst = (Get-Date).AddHours(9).ToString("yyyy.MM.dd_HH.mm")
          echo "VERSION=$kst" >> $env:GITHUB_OUTPUT

      - name: info
        run: |
          echo "tag_name: v${{ steps.version_tag.outputs.VERSION }}"
          echo "release_name: v${{ steps.version_tag.outputs.VERSION }}"

      - name: Build
        run: cargo build --release --verbose
        env:
          PLAYBRIDGE_VERSION: v${{ steps.version_tag.outputs.VERSION }}

      - name: List build directory
        run: dir target\release\

      - name: Create release and upload assets
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.version_tag.outputs.VERSION }}
          name: v${{ steps.version_tag.outputs.VERSION }}
          files: |
            target/release/PlayBridgeADB.exe
            PlayBridgeConfig.bat
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
